sudo: false

language: node_js

node_js:
  - '12.3.1'

cache:
  directories:
    - node_modules

notifications:
  email: false

# Set DISPLAY for Xvfb
env:
  - DISPLAY=:99.0

# Use APT Addon to install Chrome
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable

addons:
    chrome: stable

# Start Xvfb so you can run headless Chrome
before_install:
  - sh -e /etc/init.d/xvfb start

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm install -g --silent @angular/cli

script:
  - ng build --prod
  - ng test --code-coverage --watch=false

after_success:
  - bash <(curl -s https://codecov.io/bash)
